const Map<String, String> ar = {
  "Search": "البحث",
  "Sign In": "تسجيل دخول",
  "Contact us": "تواصل معنا",
  "Rate Us": "قيمنا",
  "Privacy policy": "سياسة الخصوصية",
  "Terms & Conditions": "الشروط والأحكام",
  "Common questions": "الأسئلة الشائعة",
  "Favourite": "المفضلة",
  "Add a discount code": "إضافة كود خصم",
  "Store details": "تفاصيل المتجر",
  "Store name": "اسم المتجر",
  " Store Link": "رابط المتجر",
  "Upload Logo": "تحميل الشعار",
  "Jpg": "(SVG او PNG , JPEG )حاول تحميل شعار أبعاد مربعة* ",
  "Discount Details": "تفاصيل الخصم",
  "Type:": "النوع:",
  "offer": "عرض",
  "Countries": "الدول",
  "copuon": "قسيمة",
  "Link offer": "رابط العرض",
  "Copun code": "كود الخصم",
  "Start Date": "تاريح البداية",
  "End Date": "تاريخ الانتهاء",
  "Date is not selected": "لم يتم تحديد التاريخ",
  " Descreotion(optional)": "التفاصيل (اختياري)",
  "Addition Terms": "لنشر كود الخصم والعرض الخاصة بمتجرك  يشترط التالي",
  "e-shop": "- أن يكون كود الخصم او العرض فعال",
  "Valid": "- أن يكون كودالخصم او العرض غير مضاف مسبقا",
  "frequent":
      "- النشر الخاص بالمتاجر الإلكترونية فقط وللحصول على مزايا إضافية تواصل معنا عبر نموذج التواصل",
  "Add": "إضافة",
  "Required": "مطلوب",
  "CANCEL": "إلغاء",
  "Ok": "تم",
  "Stores": "المتاجر",
  "Home": "الرئيسية",
  "Menu": "قائمة",
  "Last Valid use:": "آخر استخدام فعال:",
  'vaild': "فعال",
  "invalid": "غير فعال",
  "Details": "التفاصيل العرض",
  "offers": "الخصم",
  "show now": "اعرض الان",
  "Login": "تسجيل الدخول",
  "Email": "الايميل",
  "password": "كلمة المرور",
  "Forget Your passwor?": "نسيت كلمة السر",
  "New User ? ": "مستخدم جديد ؟",
  "Sign Up": "إنشاء حساب",
  "UserName": "الإسم",
  "Sign": "تسجيل جديد",
  "Done": "تم",
  "Add Coupon": "إضافة قسيمة",
  "Log Out": "تسجيل خروح",
  "COPIED": "تم نسخ",
  "Sorry": "عذراً",
  "Content": "لا يمكنك إضافة قسيمتك  الا عند  تسجيل الدخول",
  "My Account": "ملفي الشخصي",
  "Edit Account": "تعديل الحساب",
  "verifiy": "الرجاء تفعيل حسابك من خلال الرابط في بريدك الاكتروني",
  "Error": "خطأ",
  "No internet connection": "لايوجد اتصال بالانترنت",
  "Username is not Empty": " اسم المستحدم لا يجب ان يكون فارغ ",
  "Eamil is not vaild": "البريد الإلكتروني غير صالح",
  "favourites": "لا توجد قسائم للمفضلة",
  "About us": "من نحن؟",
  "Categories": "التصنيفات",
  "All": "الكل",
  "Visit": "زيارة الموقع",
  "Does": "هل تعمل هذه القسيمة",
  "Profile": "المزيد",
  "Language": "اللغة",
  "Name": "الاسم",
  "Update": "تعديل",
  "Send it again": "إرسال مرة اخرى",
  "Go Home": "الذهاب للمفضلة",
  "You can browse coupons now": "يمكنك تصفح القسائم الآن",
  "currently in the favourites": "لا يوجد قسائم حالياً في المفضلة",
  "Wrong": "خطأ",
  "successfully registered": "تم تسجيل حسابك بنجاح",
  "This email has already been registered": "تم تسجيل بهذا الايميل مسبقا",
  "Check input fields": "تحقق من الإدخال",
  "Your account has been successfully modified": "تم تعديل حسابك بنجاح",
  "You are logged in successfully": "تم تسجيل  الدخول بنجاح",
  "Not Found": "غير موجود",
  "wrong password": "كلمة مرور خاطئة",
  "Password must be greater than 6": " كلمة المرور يجب ان تكون اكبر من 6 ",
  "Forgot your password?": "نسيت كلمة المرور؟",
  "Check your verify account": "تحقق من تأكيد حسابك",
  "ForgetPassword": "استعادة كلمة المرور",
  "Send": "ارسال",
  "Please":
      "يرجى إضافة بريدك الإلكتروني المسجل إلينا حتى نتمكن من إرسال رابط استعادة كلمة المرور",
  "You can add coupons to your favourite when you log in":
      "يمكنك إضافة كوبونات إلى المفضلة عند تسجيل الدخول",
  "Store already exists": "المتجر موجود مسبقا",
  "Check all entries": "تحقق من المدخلات",
  "Your request has been submitted successfully": "تم تقديم طلبك بنجاح",
  "Subject": "موضوع الرسالة",
  "Copy Code": "نسخ الكود",
  "SEND": "إرسال",
  "SubjectDes": "تفاصيل الرسالة",
  "Message sent successfully.": "تم ارسال الرسالة بنجاح.",
  "Best Stores": "المتاجر المميزة",
  "Welcome": "مرحبا",
  "Chose": "اختر الدولة التي تريد قسميتها",
  "No result":"لا يوجد نتائج بحث"
};
