const Map<String, String> en = {
  "Search": "Search",
  "Sign In": "Sign In ",
  "Contact us": "Contact us",
  "Rate Us": "Rate Us",
  "Privacy policy": "Privacy policy",
  "Terms & Conditions": "Terms & Conditions",
  "Common questions": "Common questions",
  "Favourite": "Favourite",
  "Add a discount code": "Add a discount code",
  "Store details": "Store details",
  "Store name": "Store name",
  "Store Link(optianl)": "Store Link(optianl)",
  "Upload Logo": "Upload Logo",
  "Jpg": "Try uploading a square dimension logo (SVG او PNG , JPEG )",
  "Discount Details": "Discount Details",
  "Type:": "Type",
  "offer": "Offer",
  "copuon": "copuon",
  "Countries": "Countries",
  "Link offer": "Link offer",
  "Copun code": "Copun code",
  "Start Date": "Start Date",
  "End Date": "End Date",
  "Date is not selected": "Date is not selected",
  " Descreotion(optional)": " Descreotion(optional)",
  "Addition Terms":
      "To Post store's offers,coupons,and promo codes ,the follwing condition should be met",
  "e-shop": "- Use a vaild code,coupon or offer",
  "Valid":
      "- You can add a new code ,copoun or offer that hasn't been posted before",
  "frequent":
      "- Posting is exclusive to online stores .  If you are interested in premium features, you can send your inquiries via 'Contact Us' forn.",
  "Add": "Add",
  "Required": "Required",
  "CANCEL": "CANCEL",
  "Ok": "Ok",
  "Stores": "Stores",
  "Home": "Home",
  "Menu": "Menu",
  "Last Valid use": "آخر استخدام صالح:",
  'Vaild': "vaild",
  "invalid": "invalid",
  "Details": "Details Offer",
  "offers": "offer",
  "show now": "show now",
  "Login": "Login",
  "Email": "Email",
  "password": "Password",
  "Forget Your passwor?": "Forget Your passwor?",
  "New User ? ": "New User ?",
  "Sign Up": "Sign Up",
  "UserName": "UserName",
  "Done": "Done",
  "Add Coupon": "Add Coupon",
  "logout": "Logout",
  "Sorry": "Sorry",
  "Content": "You can only add your coupon when you log in.",
  "My Account": "My Account",
  "Edit Account": "Edit Account",
  "verifiy": "Verifiy your account through your email link",
  "Error": "Error",
  "No internet connection": "No internet connection",
  "Username is not Empty": "Username is not Empty",
  'Eamil is not vaild': "Eamil is not vaild",
  "favourites": "There are no coupons for favourites",
  "About us": "About us",
  "Categories": "Categories",
  "All": "All",
  "Visit": "Visit Website",
  "Does": "Does this coupon valid",
  "Profile": "More",
  "Language": "Language",
  "Name": "Name",
  "Update": "Update",
  "Send it again": "Send it again",
  "Go Home": "Go Home",
  "You can browse coupons now": "You can browse coupons now",
  "currently in the favourites":
      "There are no coupons currently in the favourites",
  "Wrong": "Wrong",
  "successfully registered": "successfully registered",
  "This email has already been registered":
      "This email has already been registered",
  "Check input fields": "Check input fields",
  "You are logged in successfully": "You are logged in successfully",
  "Not Found": "Not Found",
  "wrong password": "wrong password",
  "Password must be greater than 6": "Password must be greater than 6",
  "Forgot your password?": "Forgot your password?",
  "Check your verify account": "Check your account confirmation",
  "ForgetPassword": "ForgetPassword",
  "Send": "Send",
  "Please":
      "Please add your registered email to us to be able to send a password recovery link",
  "You can add coupons to your favourite when you log in":
      "You can add coupons to your favourite when you log in",
  "Store already exists": "Store already exists",
  "Check all entries": "Check all entries",
  "Your request has been submitted successfully":
      "Your request has been submitted successfully",
  "Subject": "Subject",
  "Copy Code": "Copy Code",
  "COPIED": "COPIED",
  "SEND": "SEND",
  "SubjectDes": "Message",
  "Message sent successfully.": "Message sent successfully.",
  "Best Stores": "Best Stores",
  "Welcome": "Welcome",
  "Chose": "Choose the country you want coupons for",
  "No result":"There are no search results"
};
